server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: f387d84c-e075-4dad-94f4-50aa31310467
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true   # 解决options预检请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许跨域的域名，可以用*表示允许任何域名使用
              - http://localhost:9001
              - http://localhost:9002
              - http://127.0.0.1:9001
              - http://127.0.0.1:9002
            allowedMethods: # 允许的跨域ajax的请求方式
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"                               # 允许跨域的请求头
            allowCredentials: true                # 是否允许cookie跨域（即 是否允许携带Cookie）
      routes:
        - id: userservice                        # 路由id，唯一即可
          uri: lb://userservice                  #负载均衡的服务名
          predicates:
            - Path=/user/**                       # 断言，路径相匹配的进行路由
            - Path=/address/**

        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - Path=/pay/**

        - id: itemservice
          uri: lb://itemservice
          predicates:
            - Path=/item/**

#        - id: searchservice
#          uri: lb://searchservice
#          predicates:
#            - Path=/search/**

